### ISSUE TITLE
#info Links Display Collapse

### ISSUE THREAD

**Issue by itsmattsoria** [grayghostvisuals/ggvpress#1]
Something that has literally no effect whatsoever visibly until you click on it and see the focus outline:
![image](https://cloud.githubusercontent.com/assets/2831517/8778675/d640af32-2ec4-11e5-9085-db9319b8590d.png)

Just a little:

```
#info a {
  display: block;
}
#info .custom-icon {
  vertical-align: top;
}
```

just cuz ;)

**Comment by grayghostvisuals** [comment]
:+1:
